# Generated by Django 4.2.7 on 2023-11-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='weapon_level_1',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='profession',
            name='weapon_level_2',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='profession',
            name='weapon_level_3',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='profession',
            name='precondition',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='profession',
            name='promotion',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='profession',
            name='vocational_skill',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='profession',
            name='weapon_aptitude_1',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='profession',
            name='weapon_aptitude_2',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='profession',
            name='weapon_aptitude_3',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
