# Generated by Django 4.2.7 on 2023-11-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='birthday',
            field=models.CharField(max_length=255, verbose_name='birthday'),
        ),
    ]
