# Generated by Django 4.2.7 on 2023-11-09 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_alter_characterstatus_character_charactergrowths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactergrowths',
            name='level',
        ),
    ]
