# Generated by Django 4.2.7 on 2023-11-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_remove_charactergrowths_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactergrowths',
            name='build',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='charactergrowths',
            name='defense',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='charactergrowths',
            name='dexterity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='charactergrowths',
            name='hp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='charactergrowths',
            name='lucky',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='charactergrowths',
            name='magic',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='charactergrowths',
            name='movement',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='charactergrowths',
            name='resistance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='charactergrowths',
            name='speed',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='charactergrowths',
            name='strong',
            field=models.FloatField(),
        ),
    ]
